### PR TITLE
readme: add link to slack create webhook doc

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by glensc** [comment]
@mallchin is this project abandoned?

**Comment by mallchin** [comment]
I haven't abandoned it per se but haven't touched it in years as it works fine for my use case.

I won't be using Slack soon so happy for someone else to take it over.

I'll see if I can wrap up any outstanding issues before then.

**Comment by glensc** [comment]
done.

you can direct users to https://github.com/glensc/dokuwiki-plugin-slacknotifier in readme and archive the project then

**Comment by glensc** [comment]
@mallchin can you deal with:
- https://github.com/mallchin/dokuwiki-slack-notifier/pull/9

**Comment by mallchin** [comment]
Closed in favour of https://github.com/glensc/dokuwiki-plugin-slacknotifier.

**Pull request closed without merging**
